# Deployment 1: Polling Application
deployment1:
  name: poll # Name of the first deployment
  image:
    repository: pranayreddy12/my-polling-app # Docker image repository for the polling app
    pullPolicy: IfNotPresent # Pull policy for the image; only pull if not already present
    tag: 10595546042 # Specific image tag (version) for the polling app

# Deployment 2: Worker Application
deployment2:
  name: worker # Name of the second deployment
  image:
    repository: pranayreddy12/my-polling-app # Docker image repository for the worker app
    pullPolicy: IfNotPresent # Pull policy for the image; only pull if not already present
    tag: 11095257672 # Specific image tag (version) for the worker app

# Deployment 3: Results Application
deployment3:
  name: results # Name of the third deployment
  image:
    repository: pranayreddy12/my-polling-app # Docker image repository for the results app
    pullPolicy: IfNotPresent # Pull policy for the image; only pull if not already present
    tag: 10605209132 # Specific image tag (version) for the results app
